services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=lucy
      - MYSQL_USER=lucy
      - MYSQL_PASSWORD=lucypass
      - MYSQL_ROOT_PASSWORD=rootpass
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/db:/var/lib/mysql
    # En prod, evitá exponer 3306 a host si no es necesario
    # ports:
    #   - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on: [db]
    environment:
      - DB_HOST=db
      - DB_DATABASE=lucy
      - DB_USERNAME=lucy
      - DB_PASSWORD=lucypass
      - TZ=America/Argentina/Cordoba
    # En prod, típicamente detrás de un proxy en :80
    ports:
      - "8085:80"
    # Sin volumes -> el código viene dentro de la imagen

  # phpMyAdmin sólo en dev; en prod, evitar
  # pma:
  #   image: phpmyadmin/phpmyadmin:latest
  #   restart: unless-stopped
  #   depends_on: [db]
  #   environment:
  #     - PMA_HOST=db
  #     - PMA_PORT=3306
  #   ports:
  #     - "8081:80"
